border:
  center:
    x: 0
    y: 0
  radius: 1000
potion:
  time: 60
  warning: 30
recipe:
  1: "GLASS"
  2: "GLASS"
  3: "GLASS"
  4: "GLASS"
  5: "GHAST_TEAR"
  6: "GLASS"
  7: "GLASS"
  8: "GLASS"
  9: "GLASS"
messages:
  enter: "&7[&aRadiationBorder&7] &cYou enter to the radiation zone"
  leave: "&7[&aRadiationBorder&7] &aYou leave from the radiation zone"
  potion-end: "&7[&aRadiationBorder&7] &aAnti-Radiation potion ends"
  potion-warning: "&7[&aRadiationBorder&7] &aAnti-Radiation potion ends in 30 seconds"
  potion-name: "&aAnti-Radiation potion"